### PR TITLE
finished functionality with limited testing

### PR DESCRIPTION
**Pull request by eeggssyy**

### CODE REVIEW

**Review by nickrevard9 — APPROVED** [review]
This is good to go

**Review by nickrevard9 — CHANGES_REQUESTED** [review]
Missed an issue with the code check meetlist/[tutorID] it has issues

**Comment by eeggssyy** [comment]
> Missed an issue with the code check meetlist/[tutorID] it has issues

can you explain?

**Comment by nickrevard9** [comment]
Let me expand it after yarn build it will not build the page I noticed that the function has the same name as review tutor "ReviewTutor" that may be the source here is the feedback my terminal gave me:



   Collecting page data  .ReferenceError: location is not defined
    at Object.<anonymous> (C:\Users\nickr\CSI3372\study-buddy-finder-group-1\study-buddy-frontend\node_modules\next\dist\client\performance-relayer.js:20:21)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (C:\Users\nickr\CSI3372\study-buddy-finder-group-1\study-buddy-frontend\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\nickr\CSI3372\study-buddy-finder-group-1\study-buddy-frontend\node_modules\next\dist\client\index.js:50:70)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
ReferenceError: location is not defined
    at Object.<anonymous> (C:\Users\nickr\CSI3372\study-buddy-finder-group-1\study-buddy-frontend\node_modules\next\dist\client\performance-relayer.js:20:21)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (C:\Users\nickr\CSI3372\study-buddy-finder-group-1\study-buddy-frontend\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\nickr\CSI3372\study-buddy-finder-group-1\study-buddy-frontend\node_modules\next\dist\client\index.js:50:70)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)

> Build error occurred
Error: Failed to collect page data for /MeetingList/[tutorID]
    at C:\Users\nickr\CSI3372\study-buddy-finder-group-1\study-buddy-frontend\node_modules\next\dist\build\utils.js:1220:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
error Command failed with exit code 1.

**Pull request merged**
